FrontEnds/WEBApi/Models/Baskets/BasketItemViewModel.cs
namespace WEBApi.Models.Baskets
{
    public class BasketItemViewModel
    {
        public int Quantity { get; set; } = 1;
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public decimal Price { get; set; }
        private decimal? DiscountAppliedPrice;

        public decimal GetCurrentPrice 
        {
            get => DiscountAppliedPrice != null ? DiscountAppliedPrice.Value : Price;
                }
        public void AppliedDiscount(decimal disCountPrice)
        {
            DiscountAppliedPrice = disCountPrice;
        }
    }
}

FrontEnds/WEBApi/Models/Baskets/BasketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace WEBApi.Models.Baskets
{
    public class BasketViewModel
    {
        public BasketViewModel()
        {
            _basketItems = new List<BasketItemViewModel>();
        }

        public string UserId { get; set; }
        public string DiscountCode { get; set; }

        public int? DiscountRate { get; set; }
        private List<BasketItemViewModel> _basketItems;

        public List<BasketItemViewModel> BasketItems
        {
            get
            {
                if (HasDiscount)
                {
                    //Örnek kurs fiyat 100 TL indirim %10
                    _basketItems.ForEach(x =>
                    {
                        var discountPrice = x.Price * ((decimal)DiscountRate.Value / 100);
                        x.AppliedDiscount(Math.Round(x.Price - discountPrice, 2));
                    });
                }
                return _basketItems;
            }
            set
            {
                _basketItems = value;
            }
        }

        public decimal TotalPrice
        {
            get => _basketItems.Sum(x => x.GetCurrentPrice);
        }

        public bool HasDiscount
        {
            get => !string.IsNullOrEmpty(DiscountCode)&& DiscountRate.HasValue;
        }

        public void CancelDiscount()
        {
            DiscountCode = null;
            DiscountRate = null;
        }

        public void ApplyDiscount(string code, int rate)
        {
            DiscountCode = code;
            DiscountRate = rate;
        }
    }
}

FrontEnds/WEBApi/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WEBApi.Models.Baskets;
using WEBApi.Services.Interfaces;

namespace WEBApi.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBasketService _basketService;

        public BasketController(ICatalogService catalogService, IBasketService basketService)
        {
            _catalogService = catalogService;
            _basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketService.Get());
        }

        public async Task<IActionResult> AddBasketItem(string courseId)
        {
            var course = await _catalogService.GetByCourseId(courseId);

            var basketItem = new BasketItemViewModel
            {
                CourseId = course.Id,
                CourseName = course.Name,
                Price = course.Price
            };
            await _basketService.AddBasketItem(basketItem);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveBasketItem(string courseId)
        {
            await _basketService.RemoveBasketItem(courseId);

            return RedirectToAction(nameof(Index));

        }

    }
}

FrontEnds/WEBApi/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WEBApi.Models.Orders;
using WEBApi.Services.Interfaces;

namespace WEBApi.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public OrderController(IBasketService basketService, IOrderService orderService)
        {
            _basketService = basketService;
            _orderService = orderService;
        }

        public async Task<IActionResult> Checkout()
        {
            var basket = await _basketService.Get();

            ViewBag.basket=basket;

            return View(new CheckOutInfoInput());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckOutInfoInput checkOutInfoInput)
        {
            //1. yol senkron iletişim
             var orderStatus = await _orderService.CreateOrder(checkOutInfoInput);
            // 2.yol asenkron iletişim
            //var orderSuspend = await _orderService.SuspendOrder(checkOutInfoInput);
            if (!orderStatus.IsSuccessful)
            {
                var basket = await _basketService.Get();

                ViewBag.basket = basket;

                ViewBag.error = orderStatus.Error;

                return View();
            }
            //1. yol senkron iletişim
            return RedirectToAction(nameof(SuccessfulCheckout), new { orderId = orderStatus.OrderId });

            //2.yol asenkron iletişim
           // return RedirectToAction(nameof(SuccessfulCheckout), new { orderId = new Random().Next(1, 1000) });
        }

        public IActionResult SuccessfulCheckout(int orderId)
        {
            ViewBag.orderId = orderId;
            return View();
        }
    }
}

FrontEnds/WEBApi/Views/Basket/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model BasketViewModel

<div class="row">

    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">

                <h5 class="card-title">Sepet</h5>

                @if (Model != null && Model.BasketItems.Any())
                {
                    <table class="table table-striped">

                        <tr>
                            <th>Ürün isim</th>
                            <th>Ürün fiyat</th>
 
                        </tr>

                        @foreach (var item in Model.BasketItems)
                        {
                            <tr>
                                <td>@item.CourseName</td>
                                                      
                            
                            <th colspan="2">@Model.TotalPrice TL</th>
                                <td>
                                    <a class="btn btn-outline-danger" asp-controller="Basket" asp-action="RemoveBasketItem" asp-route-courseId="@item.CourseId">sil</a>
                                
                                </td>
                            
                            </tr>
                        }

                       


                    </table>

                         <a class="btn btn-outline-success" asp-controller="Order" asp-action="Checkout">Ödeme bilgileri</a>
                         <a class="btn btn-outline-info" asp-controller="Home" asp-action="Index">Ürünlere Dön</a>
                }
                else
                {
                    <div class="alert alert-info">Sepet boş</div>
                }
            </div>
        </div>
    </div>
</div>